version: "3"

services:
  server1:
    image: orientdb:latest
    container_name: server1
    volumes:
    - ./config:/opt/orientdb/config
    ports:
    - 2424:2424
    environment:
    - ORIENTDB_ROOT_PASSWORD=root
  server2:
    image: orientdb:latest
    container_name: server2
    volumes:
    - ./config:/opt/orientdb/config
    ports:
    - 2424:2424
    environment:
    - ORIENTDB_ROOT_PASSWORD=root